import { Share } from "../types";
export const shareData: Share[] = [
  {
    id: 1,
    shareName: "Share 1",
    unitPrice: 100,
    quantity: 100,
    transactionType: "Purchased",
    status: null,
    image: null,
  },
  {
    id: 2,
    shareName: "Share 2",
    unitPrice: 120,
    quantity: 80,
    transactionType: "Sell",
    status: "profit",
    image: null,
  },
  {
    id: 3,
    shareName: "Share 3",
    unitPrice: 90,
    quantity: 50,
    transactionType: "Sell",
    status: "loss",
    image: null,
  },
  {
    id: 4,
    shareName: "Share 4",
    unitPrice: 150,
    quantity: 200,
    transactionType: "Purchased",
    status: null,
    image: null,
  },
  {
    id: 5,
    shareName: "Share 5",
    unitPrice: 110,
    quantity: 60,
    transactionType: "Sell",
    status: "profit",
    image: null,
  },
  {
    id: 6,
    shareName: "Share 6",
    unitPrice: 95,
    quantity: 75,
    transactionType: "Sell",
    status: "loss",
    image: null,
  },
  {
    id: 7,
    shareName: "Share 7",
    unitPrice: 130,
    quantity: 90,
    transactionType: "Purchased",
    status: null,
    image: null,
  },
  {
    id: 8,
    shareName: "Share 8",
    unitPrice: 85,
    quantity: 110,
    transactionType: "Sell",
    status: "profit",
    image: null,
  },
  {
    id: 9,
    shareName: "Share 9",
    unitPrice: 105,
    quantity: 70,
    transactionType: "Sell",
    status: "loss",
    image: null,
  },
  {
    id: 10,
    shareName: "Share 10",
    unitPrice: 140,
    quantity: 100,
    transactionType: "Purchased",
    status: null,
    image: null,
  },
];
