import { Transaction } from "../components/transaction/type";
import { User } from "../types";
export const transactionData: Transaction[] = [
  {
    id: "DEP-10534",
    type: "Deposit",
    subtype: "Monthly contribution ",
    amount: "₹1,000",
    date: "Nov 10, 2023",
    paymentMethod: "Bank Transfer",
    status: "Approved",
    approvedBy: "Admin (John Smith)",
    approvalDate: "Nov 10, 2023, 16:15:42",
    notes: "Monthly contribution for November",
  },
  {
    id: "INST-8762",
    type: "Installment",
    subtype: "Loan Repayment",
    amount: "₹1,330",
    date: "Nov 05, 2023",
    paymentMethod: "UPI",
    status: "Approved",
    approvedBy: "Admin (Sarah Johnson)",
    approvalDate: "Nov 05, 2023, 11:05:33",
    notes: "Loan repayment for November",
  },
  {
    id: "LOAN-4329",
    type: "Loan",
    subtype: "Loan disbursement ",
    amount: "₹15,000",
    date: "Oct 20, 2023",
    paymentMethod: "Bank Transfer",
    status: "Approved",
    approvedBy: "Admin (John Smith)",
    approvalDate: "Oct 20, 2023, 15:10:45",
    notes: "Personal loan - approved as per policy",
  },
  {
    id: "INST-7631",
    type: "Installment",
    subtype: "Loan Repayment",
    amount: "₹1,330",
    date: "Oct 15, 2023",
    paymentMethod: "Cash",
    status: "Approved",
    approvedBy: "Admin (Sarah Johnson)",
    approvalDate: "Oct 15, 2023, 10:30:12",
    notes: "Loan repayment for October",
  },
  {
    id: "DEP-10349",
    type: "Deposit",
    subtype: "Monthly contribution ",
    amount: "₹1,000",
    date: "Oct 10, 2023",
    paymentMethod: "UPI",
    status: "Approved",
    approvedBy: "Admin (John Smith)",
    approvalDate: "Oct 10, 2023, 17:05:33",
    notes: "Monthly contribution for October",
  },
  {
    id: "SHARE-2341",
    type: "Share Purchase",
    subtype: "Investment",
    amount: "₹5,000",
    date: "Nov 12, 2023",
    paymentMethod: "Bank Transfer",
    status: "Pending",
    approvedBy: "Pending Approval",
    approvalDate: "Pending",
    notes: "Purchase of 50 shares @ ₹100 each",
  },
  {
    id: "LOAN-8765",
    type: "Loan Application",
    subtype: "Loan request ",
    amount: "₹20,000",
    date: "Nov 08, 2023",
    paymentMethod: "N/A",
    status: "Pending",
    approvedBy: "Pending Approval",
    approvalDate: "Pending",
    notes: "Personal loan application - under review",
  },
];

export const users: User[] = [
  {
    name: "Rahul Sharma",
    email: "rahul.s@example.com",
    initials: "RS",
    id: "BF-1001",
    depositAmount: "₹6,000",
    depositDuration: "6 months",
    loanAmount: "₹15,000",
    loanStatus: "Active",
    status: "Active",
  },
  {
    name: "Priya Patel",
    email: "priya.p@example.com",
    initials: "PP",
    id: "BF-1002",
    depositAmount: "₹8,000",
    depositDuration: "8 months",
    loanAmount: "₹20,000",
    loanStatus: "Pending",
    status: "Active",
  },
  {
    name: "Amit Kumar",
    email: "amit.k@example.com",
    initials: "AK",
    id: "BF-1003",
    depositAmount: "₹12,000",
    depositDuration: "12 months",
    loanAmount: "₹18,000",
    loanStatus: "Active",
    status: "Active",
  },
  {
    name: "Neha Singh",
    email: "neha.s@example.com",
    initials: "NS",
    id: "BF-1004",
    depositAmount: "₹10,000",
    depositDuration: "10 months",
    loanAmount: "₹0",
    loanStatus: "None",
    status: "Active",
  },
];
